

2020-08-17 13:42:29,262 [4]  - Encountered unknown log level Information, writing out as Info

2020-08-17 13:42:29,271 [4]  - [INFO] logger!

2020-08-17 13:42:29,273 [4]  - [WARN] logger!

2020-08-17 13:42:29,275 [4]  - [ERROR] logger!

2020-08-17 13:42:29,276 [4]  - [CRITICAL] logger!

2020-08-17 14:14:44,300 [5]  - Encountered unknown log level Information, writing out as Info

2020-08-17 14:14:44,307 [5]  - [INFO] logger!

2020-08-17 14:14:44,309 [5]  - [WARN] logger!

2020-08-17 14:14:44,311 [5]  - [ERROR] logger!

2020-08-17 14:14:44,313 [5]  - [CRITICAL] logger!

2020-08-17 14:43:05,408 [4]  - Encountered unknown log level Information, writing out as Info

2020-08-17 14:43:05,422 [4]  - [INFO] logger!

2020-08-17 14:43:05,425 [4]  - [WARN] logger!

2020-08-17 14:43:05,426 [4]  - [ERROR] logger!

2020-08-17 14:43:05,428 [4]  - [CRITICAL] logger!

2020-08-17 14:48:15,721 [5]  - System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at UI.WebStore.Controllers.HomeController.Index() in C:\GreekBrains\WebStore_2020_Home_Work\UI\WebStore_2020\Controllers\HomeController.cs:line 31
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at WebStore.Startup.<>c.<<UseSampleErrorCheck>b__4_0>d.MoveNext() in C:\GreekBrains\WebStore_2020_Home_Work\UI\WebStore_2020\Startup.cs:line 160
--- End of stack trace from previous location where exception was thrown ---
   at UI.WebStore.Infrastructure.TokenMiddleware.InvokeAsync(HttpContext context) in C:\GreekBrains\WebStore_2020_Home_Work\UI\WebStore_2020\Infrastructure\TokenMiddleware.cs:line 25
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at WebStore.Services.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\GreekBrains\WebStore_2020_Home_Work\Services\WebStore.Services\ErrorHandlingMiddleware.cs:line 24

2020-08-17 14:48:15,765 [5]  - An unhandled exception has occurred while executing the request.

2020-08-17 15:25:00,811 [4]  - System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at UI.WebStore.Controllers.HomeController.Index() in C:\GreekBrains\WebStore_2020_Home_Work\UI\WebStore_2020\Controllers\HomeController.cs:line 31
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at WebStore.Startup.<>c.<<UseSampleErrorCheck>b__4_0>d.MoveNext() in C:\GreekBrains\WebStore_2020_Home_Work\UI\WebStore_2020\Startup.cs:line 162
--- End of stack trace from previous location where exception was thrown ---
   at UI.WebStore.Infrastructure.TokenMiddleware.InvokeAsync(HttpContext context) in C:\GreekBrains\WebStore_2020_Home_Work\UI\WebStore_2020\Infrastructure\TokenMiddleware.cs:line 25
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at WebStore.Services.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\GreekBrains\WebStore_2020_Home_Work\Services\WebStore.Services\ErrorHandlingMiddleware.cs:line 24

2020-08-17 15:25:00,848 [4]  - An unhandled exception has occurred while executing the request.

2020-08-17 15:30:54,699 [4]  - System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at UI.WebStore.Controllers.HomeController.Index() in C:\GreekBrains\WebStore_2020_Home_Work\UI\WebStore_2020\Controllers\HomeController.cs:line 31
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at WebStore.Startup.<>c.<<UseSampleErrorCheck>b__4_0>d.MoveNext() in C:\GreekBrains\WebStore_2020_Home_Work\UI\WebStore_2020\Startup.cs:line 162
--- End of stack trace from previous location where exception was thrown ---
   at UI.WebStore.Infrastructure.TokenMiddleware.InvokeAsync(HttpContext context) in C:\GreekBrains\WebStore_2020_Home_Work\UI\WebStore_2020\Infrastructure\TokenMiddleware.cs:line 25
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at WebStore.Services.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\GreekBrains\WebStore_2020_Home_Work\Services\WebStore.Services\ErrorHandlingMiddleware.cs:line 24

2020-08-17 15:30:54,737 [4]  - An unhandled exception has occurred while executing the request.

2020-08-17 15:34:01,204 [4]  - System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at UI.WebStore.Controllers.HomeController.Index() in C:\GreekBrains\WebStore_2020_Home_Work\UI\WebStore_2020\Controllers\HomeController.cs:line 31
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at WebStore.Startup.<>c.<<UseSampleErrorCheck>b__4_0>d.MoveNext() in C:\GreekBrains\WebStore_2020_Home_Work\UI\WebStore_2020\Startup.cs:line 162
--- End of stack trace from previous location where exception was thrown ---
   at UI.WebStore.Infrastructure.TokenMiddleware.InvokeAsync(HttpContext context) in C:\GreekBrains\WebStore_2020_Home_Work\UI\WebStore_2020\Infrastructure\TokenMiddleware.cs:line 25
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at WebStore.Services.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\GreekBrains\WebStore_2020_Home_Work\Services\WebStore.Services\ErrorHandlingMiddleware.cs:line 24

2020-08-17 15:34:01,242 [4]  - An unhandled exception has occurred while executing the request.

2020-08-17 15:37:16,782 [5]  - System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at UI.WebStore.Controllers.HomeController.Index() in C:\GreekBrains\WebStore_2020_Home_Work\UI\WebStore_2020\Controllers\HomeController.cs:line 31
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at WebStore.Startup.<>c.<<UseSampleErrorCheck>b__4_0>d.MoveNext() in C:\GreekBrains\WebStore_2020_Home_Work\UI\WebStore_2020\Startup.cs:line 162
--- End of stack trace from previous location where exception was thrown ---
   at UI.WebStore.Infrastructure.TokenMiddleware.InvokeAsync(HttpContext context) in C:\GreekBrains\WebStore_2020_Home_Work\UI\WebStore_2020\Infrastructure\TokenMiddleware.cs:line 25
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at WebStore.Services.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\GreekBrains\WebStore_2020_Home_Work\Services\WebStore.Services\ErrorHandlingMiddleware.cs:line 24

2020-08-17 15:37:16,822 [5]  - Connection ID "18374686502757072907", Request ID "8000000c-0005-ff00-b63f-84710c7967bb": An unhandled exception was thrown by the application.

2020-08-17 15:40:58,787 [4]  - Encountered unknown log level Information, writing out as Info

2020-08-17 15:40:58,794 [4]  - [INFO] logger!

2020-08-17 15:40:58,796 [4]  - [WARN] logger!

2020-08-17 15:40:58,798 [4]  - [ERROR] logger!

2020-08-17 15:40:58,800 [4]  - [CRITICAL] logger!

2020-08-17 15:40:58,899 [4]  - System.ApplicationException: Тест сообщений об ошибках
   at UI.WebStore.Controllers.HomeController.Index() in C:\GreekBrains\WebStore_2020_Home_Work\UI\WebStore_2020\Controllers\HomeController.cs:line 40
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at WebStore.Startup.<>c.<<UseSampleErrorCheck>b__4_0>d.MoveNext() in C:\GreekBrains\WebStore_2020_Home_Work\UI\WebStore_2020\Startup.cs:line 162
--- End of stack trace from previous location where exception was thrown ---
   at UI.WebStore.Infrastructure.TokenMiddleware.InvokeAsync(HttpContext context) in C:\GreekBrains\WebStore_2020_Home_Work\UI\WebStore_2020\Infrastructure\TokenMiddleware.cs:line 25
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at WebStore.Services.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\GreekBrains\WebStore_2020_Home_Work\Services\WebStore.Services\ErrorHandlingMiddleware.cs:line 24

2020-08-17 15:40:58,929 [4]  - Connection ID "18374686528526876684", Request ID "8000000d-000b-ff00-b63f-84710c7967bb": An unhandled exception was thrown by the application.

2020-08-17 15:46:41,088 [5]  - Encountered unknown log level Information, writing out as Info

2020-08-17 15:46:41,101 [5]  - [INFO] logger!

2020-08-17 15:46:41,103 [5]  - [WARN] logger!

2020-08-17 15:46:41,105 [5]  - [ERROR] logger!

2020-08-17 15:46:41,107 [5]  - [CRITICAL] logger!

2020-08-17 15:46:41,203 [5]  - System.ApplicationException: Тест сообщений об ошибках
   at UI.WebStore.Controllers.HomeController.Index() in C:\GreekBrains\WebStore_2020_Home_Work\UI\WebStore_2020\Controllers\HomeController.cs:line 40
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at WebStore.Startup.<>c.<<UseSampleErrorCheck>b__4_0>d.MoveNext() in C:\GreekBrains\WebStore_2020_Home_Work\UI\WebStore_2020\Startup.cs:line 166
--- End of stack trace from previous location where exception was thrown ---
   at UI.WebStore.Infrastructure.TokenMiddleware.InvokeAsync(HttpContext context) in C:\GreekBrains\WebStore_2020_Home_Work\UI\WebStore_2020\Infrastructure\TokenMiddleware.cs:line 25
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at WebStore.Services.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\GreekBrains\WebStore_2020_Home_Work\Services\WebStore.Services\ErrorHandlingMiddleware.cs:line 24

2020-08-17 15:46:41,234 [5]  - An unhandled exception has occurred while executing the request.

2020-08-17 15:47:29,666 [4]  - Encountered unknown log level Information, writing out as Info

2020-08-17 15:47:29,674 [4]  - [INFO] logger!

2020-08-17 15:47:29,676 [4]  - [WARN] logger!

2020-08-17 15:47:29,679 [4]  - [ERROR] logger!

2020-08-17 15:47:29,681 [4]  - [CRITICAL] logger!

2020-08-17 15:47:29,778 [4]  - System.ApplicationException: Тест сообщений об ошибках
   at UI.WebStore.Controllers.HomeController.Index() in C:\GreekBrains\WebStore_2020_Home_Work\UI\WebStore_2020\Controllers\HomeController.cs:line 40
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at WebStore.Startup.<>c.<<UseSampleErrorCheck>b__4_0>d.MoveNext() in C:\GreekBrains\WebStore_2020_Home_Work\UI\WebStore_2020\Startup.cs:line 166
--- End of stack trace from previous location where exception was thrown ---
   at UI.WebStore.Infrastructure.TokenMiddleware.InvokeAsync(HttpContext context) in C:\GreekBrains\WebStore_2020_Home_Work\UI\WebStore_2020\Infrastructure\TokenMiddleware.cs:line 25
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at WebStore.Services.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\GreekBrains\WebStore_2020_Home_Work\Services\WebStore.Services\ErrorHandlingMiddleware.cs:line 24

2020-08-17 15:47:29,808 [4]  - An unhandled exception has occurred while executing the request.

2020-08-17 16:15:42,180 [4]  - Encountered unknown log level Information, writing out as Info

2020-08-17 16:15:42,187 [4]  - [INFO] logger!

2020-08-17 16:15:42,189 [4]  - [WARN] logger!

2020-08-17 16:15:42,191 [4]  - [ERROR] logger!

2020-08-17 16:15:42,192 [4]  - [CRITICAL] logger!

2020-08-17 16:15:42,289 [4]  - System.ApplicationException: Тест сообщений об ошибках
   at UI.WebStore.Controllers.HomeController.Index() in C:\GreekBrains\WebStore_2020_Home_Work\UI\WebStore_2020\Controllers\HomeController.cs:line 40
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at WebStore.Startup.<>c.<<UseSampleErrorCheck>b__4_0>d.MoveNext() in C:\GreekBrains\WebStore_2020_Home_Work\UI\WebStore_2020\Startup.cs:line 166
--- End of stack trace from previous location where exception was thrown ---
   at UI.WebStore.Infrastructure.TokenMiddleware.InvokeAsync(HttpContext context) in C:\GreekBrains\WebStore_2020_Home_Work\UI\WebStore_2020\Infrastructure\TokenMiddleware.cs:line 25
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at WebStore.Services.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\GreekBrains\WebStore_2020_Home_Work\Services\WebStore.Services\ErrorHandlingMiddleware.cs:line 24

2020-08-17 16:15:42,327 [4]  - An unhandled exception has occurred while executing the request.

2020-08-17 16:17:23,832 [4]  - Encountered unknown log level Information, writing out as Info

2020-08-17 16:17:23,840 [4]  - [INFO] logger!

2020-08-17 16:17:23,841 [4]  - [WARN] logger!

2020-08-17 16:17:23,842 [4]  - [ERROR] logger!

2020-08-17 16:17:23,844 [4]  - [CRITICAL] logger!

2020-08-17 16:17:23,925 [4]  - System.ApplicationException: Тест сообщений об ошибках
   at UI.WebStore.Controllers.HomeController.Index() in C:\GreekBrains\WebStore_2020_Home_Work\UI\WebStore_2020\Controllers\HomeController.cs:line 40
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at WebStore.Startup.<>c.<<UseSampleErrorCheck>b__4_0>d.MoveNext() in C:\GreekBrains\WebStore_2020_Home_Work\UI\WebStore_2020\Startup.cs:line 166
--- End of stack trace from previous location where exception was thrown ---
   at UI.WebStore.Infrastructure.TokenMiddleware.InvokeAsync(HttpContext context) in C:\GreekBrains\WebStore_2020_Home_Work\UI\WebStore_2020\Infrastructure\TokenMiddleware.cs:line 25
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at WebStore.Services.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\GreekBrains\WebStore_2020_Home_Work\Services\WebStore.Services\ErrorHandlingMiddleware.cs:line 24

2020-08-17 16:17:23,950 [4]  - An unhandled exception has occurred while executing the request.

2020-08-17 16:19:07,652 [4]  - Encountered unknown log level Information, writing out as Info

2020-08-17 16:19:10,362 [4]  - [INFO] logger!

2020-08-17 16:19:10,366 [4]  - [WARN] logger!

2020-08-17 16:19:10,369 [4]  - [ERROR] logger!

2020-08-17 16:19:10,372 [4]  - [CRITICAL] logger!

2020-08-17 16:19:16,768 [4]  - System.ApplicationException: Тест сообщений об ошибках
   at UI.WebStore.Controllers.HomeController.Index() in C:\GreekBrains\WebStore_2020_Home_Work\UI\WebStore_2020\Controllers\HomeController.cs:line 40
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at WebStore.Startup.<>c.<<UseSampleErrorCheck>b__4_0>d.MoveNext() in C:\GreekBrains\WebStore_2020_Home_Work\UI\WebStore_2020\Startup.cs:line 166
--- End of stack trace from previous location where exception was thrown ---
   at UI.WebStore.Infrastructure.TokenMiddleware.InvokeAsync(HttpContext context) in C:\GreekBrains\WebStore_2020_Home_Work\UI\WebStore_2020\Infrastructure\TokenMiddleware.cs:line 25
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at WebStore.Services.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\GreekBrains\WebStore_2020_Home_Work\Services\WebStore.Services\ErrorHandlingMiddleware.cs:line 24

2020-08-17 16:19:19,197 [4]  - An unhandled exception has occurred while executing the request.

2020-08-17 16:21:58,934 [4]  - Encountered unknown log level Information, writing out as Info

2020-08-17 16:21:58,941 [4]  - [INFO] logger!

2020-08-17 16:21:58,943 [4]  - [WARN] logger!

2020-08-17 16:21:58,945 [4]  - [ERROR] logger!

2020-08-17 16:21:58,946 [4]  - [CRITICAL] logger!

2020-08-17 16:21:59,029 [4]  - System.ApplicationException: Тест сообщений об ошибках
   at UI.WebStore.Controllers.HomeController.Index() in C:\GreekBrains\WebStore_2020_Home_Work\UI\WebStore_2020\Controllers\HomeController.cs:line 40
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at WebStore.Startup.<>c.<<UseSampleErrorCheck>b__4_0>d.MoveNext() in C:\GreekBrains\WebStore_2020_Home_Work\UI\WebStore_2020\Startup.cs:line 166
--- End of stack trace from previous location where exception was thrown ---
   at UI.WebStore.Infrastructure.TokenMiddleware.InvokeAsync(HttpContext context) in C:\GreekBrains\WebStore_2020_Home_Work\UI\WebStore_2020\Infrastructure\TokenMiddleware.cs:line 25
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at WebStore.Services.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\GreekBrains\WebStore_2020_Home_Work\Services\WebStore.Services\ErrorHandlingMiddleware.cs:line 24

2020-08-17 16:21:59,055 [4]  - An unhandled exception has occurred while executing the request.

2020-08-17 16:23:29,087 [9]  - Encountered unknown log level Information, writing out as Info

2020-08-17 16:23:29,094 [9]  - [INFO] logger!

2020-08-17 16:23:29,096 [9]  - [WARN] logger!

2020-08-17 16:23:29,098 [9]  - [ERROR] logger!

2020-08-17 16:23:29,100 [9]  - [CRITICAL] logger!

2020-08-17 16:23:29,189 [9]  - System.ApplicationException: Тест сообщений об ошибках
   at UI.WebStore.Controllers.HomeController.Index() in C:\GreekBrains\WebStore_2020_Home_Work\UI\WebStore_2020\Controllers\HomeController.cs:line 40
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at WebStore.Startup.<>c.<<UseSampleErrorCheck>b__4_0>d.MoveNext() in C:\GreekBrains\WebStore_2020_Home_Work\UI\WebStore_2020\Startup.cs:line 166
--- End of stack trace from previous location where exception was thrown ---
   at UI.WebStore.Infrastructure.TokenMiddleware.InvokeAsync(HttpContext context) in C:\GreekBrains\WebStore_2020_Home_Work\UI\WebStore_2020\Infrastructure\TokenMiddleware.cs:line 25
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at WebStore.Services.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\GreekBrains\WebStore_2020_Home_Work\Services\WebStore.Services\ErrorHandlingMiddleware.cs:line 24

2020-08-17 16:23:29,215 [9]  - An unhandled exception has occurred while executing the request.

2020-08-17 16:25:34,990 [4]  - Encountered unknown log level Information, writing out as Info

2020-08-17 16:25:34,998 [4]  - [INFO] logger!

2020-08-17 16:25:34,999 [4]  - [WARN] logger!

2020-08-17 16:25:35,001 [4]  - [ERROR] logger!

2020-08-17 16:25:35,002 [4]  - [CRITICAL] logger!

2020-08-17 16:25:35,084 [4]  - System.ApplicationException: Тест сообщений об ошибках
   at UI.WebStore.Controllers.HomeController.Index() in C:\GreekBrains\WebStore_2020_Home_Work\UI\WebStore_2020\Controllers\HomeController.cs:line 40
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at WebStore.Startup.<>c.<<UseSampleErrorCheck>b__4_0>d.MoveNext() in C:\GreekBrains\WebStore_2020_Home_Work\UI\WebStore_2020\Startup.cs:line 166
--- End of stack trace from previous location where exception was thrown ---
   at UI.WebStore.Infrastructure.TokenMiddleware.InvokeAsync(HttpContext context) in C:\GreekBrains\WebStore_2020_Home_Work\UI\WebStore_2020\Infrastructure\TokenMiddleware.cs:line 25
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at WebStore.Services.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\GreekBrains\WebStore_2020_Home_Work\Services\WebStore.Services\ErrorHandlingMiddleware.cs:line 24

2020-08-17 16:25:35,111 [4]  - An unhandled exception has occurred while executing the request.

2020-08-17 16:27:14,374 [4]  - Encountered unknown log level Information, writing out as Info

2020-08-17 16:27:14,381 [4]  - [INFO] logger!

2020-08-17 16:27:14,383 [4]  - [WARN] logger!

2020-08-17 16:27:14,384 [4]  - [ERROR] logger!

2020-08-17 16:27:14,386 [4]  - [CRITICAL] logger!

2020-08-17 16:27:14,468 [4]  - System.ApplicationException: Тест сообщений об ошибках
   at UI.WebStore.Controllers.HomeController.Index() in C:\GreekBrains\WebStore_2020_Home_Work\UI\WebStore_2020\Controllers\HomeController.cs:line 40
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at WebStore.Startup.<>c.<<UseSampleErrorCheck>b__4_0>d.MoveNext() in C:\GreekBrains\WebStore_2020_Home_Work\UI\WebStore_2020\Startup.cs:line 166
--- End of stack trace from previous location where exception was thrown ---
   at UI.WebStore.Infrastructure.TokenMiddleware.InvokeAsync(HttpContext context) in C:\GreekBrains\WebStore_2020_Home_Work\UI\WebStore_2020\Infrastructure\TokenMiddleware.cs:line 25
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at WebStore.Services.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\GreekBrains\WebStore_2020_Home_Work\Services\WebStore.Services\ErrorHandlingMiddleware.cs:line 24

2020-08-17 16:27:14,494 [4]  - An unhandled exception has occurred while executing the request.

2020-08-17 16:28:42,823 [4]  - Encountered unknown log level Information, writing out as Info

2020-08-17 16:28:42,831 [4]  - [INFO] logger!

2020-08-17 16:28:42,832 [4]  - [WARN] logger!

2020-08-17 16:28:42,834 [4]  - [ERROR] logger!

2020-08-17 16:28:42,835 [4]  - [CRITICAL] logger!

2020-08-17 16:28:42,934 [4]  - System.ApplicationException: Тест сообщений об ошибках
   at UI.WebStore.Controllers.HomeController.Index() in C:\GreekBrains\WebStore_2020_Home_Work\UI\WebStore_2020\Controllers\HomeController.cs:line 40
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at WebStore.Startup.<>c.<<UseSampleErrorCheck>b__4_0>d.MoveNext() in C:\GreekBrains\WebStore_2020_Home_Work\UI\WebStore_2020\Startup.cs:line 166
--- End of stack trace from previous location where exception was thrown ---
   at UI.WebStore.Infrastructure.TokenMiddleware.InvokeAsync(HttpContext context) in C:\GreekBrains\WebStore_2020_Home_Work\UI\WebStore_2020\Infrastructure\TokenMiddleware.cs:line 25
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at WebStore.Services.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\GreekBrains\WebStore_2020_Home_Work\Services\WebStore.Services\ErrorHandlingMiddleware.cs:line 24

2020-08-17 16:28:42,966 [4]  - An unhandled exception has occurred while executing the request.

